name: Scheduled update-day diff tool

on:
  schedule:
    - cron: "35 11 * * 3"

jobs:
  run-diff-task:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Get abex releases
        id: get_releases
        uses: yakubique/github-releases@v1.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          repository: abextm/osrs-cache
          sort: "desc"

      - name: Get renderer workflow runs
        id: get_render_runs
        uses: satvik-s/workflow-runs-action@v0.0.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          github-repository: osrs-wiki/osrs-renderer-tools

      - name: Download render artifacts
        uses: actions/download-artifact@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          repository: osrs-wiki/osrs-renderer-tools
          run-id: ${{ fromJson(steps.get_render_runs.outputs.runs-summary).workflow_runs[0].id }}

      - name: Run task
        run: npm run start differences -- --oldCache ${{ fromJson(steps.get_releases.outputs.releases)[1] }} --newCache ${{ fromJson(steps.get_releases.outputs.releases)[0] }}

      - name: Upload Output
        uses: actions/upload-artifact@v4
        with:
          name: out-${{ github.run_id }}-${{ github.run_attempt }}
          path: out/
