name: Run Cache Tasks

on:
  workflow_dispatch:
    inputs:
      task:
        description: "Task type"
        required: true
        default: "differences"
        type: choice
        options:
          - differences
          - combatAchievements
          - clues

      pages:
        description: "Include pages (optional)"
        default: "false"
        required: false

      examines:
        description: "Include examines (optional)"
        default: "false"
        required: false

      renders:
        description: "Include renders (optional)"
        required: false
        default: "false"

      oldCache:
        description: "Old cache date (optional)"
        required: false

      newCache:
        description: "New cache date (optional)"
        required: false

      update:
        description: "The game update title (optional)"
        default: "auto"
        required: false

      updateDate:
        description: "The game update date (optional)"
        default: "auto"
        required: false

jobs:
  run-cache-tasks:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Get abex releases
        id: get_releases
        if: github.event.inputs.newCache == ''
        uses: yakubique/github-releases@v1.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          repository: abextm/osrs-cache
          sort: "desc"

      - name: Get renderer workflow runs
        id: get_render_runs
        uses: satvik-s/workflow-runs-action@v0.0.3
        env:
          GITHUB_TOKEN: ${{ secrets.PUBLISH_PACKAGES }}
        with:
          github-repository: osrs-wiki/osrs-renderer-tools

      - name: Check if workflow run is from today
        id: check_date
        run: |
          WORKFLOW_DATE=$(echo '${{ fromJson(steps.get_render_runs.outputs.runs-summary).workflow_runs[0].created_at }}' | cut -d'T' -f1)
          TODAY_DATE=$(date -u +"%Y-%m-%d")
          if [ "$WORKFLOW_DATE" == "$TODAY_DATE" ]; then
            echo "is_today=true" >> $GITHUB_OUTPUT
          else
            echo "is_today=false" >> $GITHUB_OUTPUT
          fi
          echo "Workflow date: $WORKFLOW_DATE, Today: $TODAY_DATE"

      - name: Download render artifacts
        if: steps.check_date.outputs.is_today == 'true'
        id: download_render_artifacts
        uses: actions/download-artifact@v4
        with:
          github-token: ${{ secrets.PUBLISH_PACKAGES }}
          path: data/
          repository: osrs-wiki/osrs-renderer-tools
          run-id: ${{ fromJson(steps.get_render_runs.outputs.runs-summary).workflow_runs[0].id }}

      - name: Run task
        env:
          TASK: ${{ github.event.inputs.task }}
          PAGES: ${{ github.event.inputs.pages }}
          EXAMINES: ${{ github.event.inputs.examines }}
          RENDERS: ${{ steps.download_render_artifacts.outputs.download-path != null && format('renders-{0}-1', fromJson(steps.get_releases.outputs.releases)[0] || github.event.inputs.newCache) || github.event.inputs.renders }}
          OLDCACHE: ${{ steps.get_releases.outputs.releases != null && fromJson(steps.get_releases.outputs.releases)[1] || github.event.inputs.oldCache }}
          NEWCACHE: ${{ steps.get_releases.outputs.releases != null && fromJson(steps.get_releases.outputs.releases)[0] || github.event.inputs.newCache }}
          UPDATE: ${{ github.event.inputs.update }}
          UPDATEDATE: ${{ github.event.inputs.updateDate }}
        run: npm run start $TASK -- --pages $PAGES --examines $EXAMINES --renders $RENDERS --oldCache $OLDCACHE --newCache $NEWCACHE --update $UPDATE --updateDate $UPDATEDATE

      - name: Upload Output
        uses: actions/upload-artifact@v4
        with:
          name: out-${{ github.run_id }}-${{ github.run_attempt }}
          path: out/
